### ISSUE TITLE
Unrecognised PST File version: 36

### ISSUE THREAD

**Issue by ramana4029** [rjohnsondev/java-libpst#18]
Hi,
  I am trying to read one of the OST files from outlook 2013, it fails with the exception 
com.pff.PSTException: Unrecognised PST File version: 36 
  This works fine with the PST's from older version of outlook. 

Is there a way or workaround to get this working.

Thanks

**Comment by ManishaDec11** [comment]
Hi All,

I tried with java-libpst-0.8.1.jar to read emails from OST file generated from Outlook 2013.
I see the same error "com.pff.PSTException: Unrecognised PST File version: 36"

Please let me know whether that issue got resolved or not.

I have an urgent requirement.

Any help will be highly appreciated.

Thanks

**Comment by rjohnsondev** [comment]
Hey,

Please try building the library from the 2013 support branch and see how
that works for you.

https://github.com/rjohnsondev/java-libpst/tree/feature/2013-ost-support?files=1

Thanks,

Richard

**Comment by ManishaDec11** [comment]
Hi Richard,

Thank you very much for the prompt response.

I prepared the library from the code and now I am able to read the .OST file,but after reading few emails it gave me below error:

com.pff.PSTException: Unable to find 50331648 is desc: true
at com.pff.PSTFile.findBtreeItem(PSTFile.java:727)
at com.pff.PSTFile.getDescriptorIndexNode(PSTFile.java:745)
at com.pff.PSTFolder.getNextChild(PSTFolder.java:290)
at main.java.com.pff.PSTFolder.getNextChild(PSTFolder.java:290)

Please help.

Thanks,
Manisha

**Comment by lfcnassif** [comment]
Seems like libpff has added info (and support) about the new OST format to the documentation back in 2013:
https://da1ba3cfdffc2404250f16d3711dfb32dcd40e96.googledrive.com/host/0B3fBvzttpiiScU9qcG5ScEZKZE0/Personal%20Folder%20File%20(PFF)%20format.pdf

**Comment by kirill-linnik** [comment]
hi guys! where you ended up with that? 0.8.1 still gives "com.pff.PSTException: Unrecognised PST File version: 36" and links you provided are all 404 :(
