### ISSUE TITLE
Unable to parse - bad table type

### ISSUE THREAD

**Issue by ggutierrezc** [rjohnsondev/java-libpst#30]
Hi guys,
I'm trying to extract information from a PST file using java-libpst and found this issue after processing several hundred entries:

PSTException: Unable to parse table, bad table type.  Unknown identifier: 0xffffffffffffffec
	at pst.PSTTable.<init>(PSTTable.java:114)
	at pst.PSTTableBC.<init>(PSTTableBC.java:54)
	at pst.PSTObject.detectAndLoadPSTObject(PSTObject.java:652)
	at pst.PSTFolder.getNextChild(PSTFolder.java:291)

Because this error ended the execution, is there a way that I can skip this entry and keep processing the other ones? There are around 30,000 emails in the input file and I don't mind if I loose the ones with this issue.

Thanks a lot.

Antonio

**Comment by rjohnsondev** [comment]
I understand this was probably too long ago (hence closing) however I have more time these days to try and address these issues, so don't hesitate to re-open if you are in a position to help me look into it further.
