### ISSUE TITLE
NullPointerException in (PSTAttachment.java:119)

### ISSUE THREAD

**Issue by stanpalatnik** [rjohnsondev/java-libpst#31]
I'm parsing a message from a PST, and running into an NPE that originates from PSTAttachment.java line 119: 
com.pff.PSTAttachment.getFileInputStream(PSTAttachment.java:119)

In the pst lib I have, line 119 consists of : 
if (attachmentDataObject.isExternalValueReference) {
..

I'm not sure if this a bug, or indicates if the message/attachment is corrupt. Should I be catching this? 

I'm using the 0.8.1 release

**Comment by rjohnsondev** [comment]
I understand this was probably too long ago (hence closing) however I have more time these days to try and address these issues, so don't hesitate to re-open if you are in a position to help me look into it further.
