### ISSUE TITLE
getBodyHTML returns empty string for some emails that actually contain text

### ISSUE THREAD

**Issue by ggutierrezc** [rjohnsondev/java-libpst#32]
While processing thousands of email, if came across that some HTML bodies are not extracted. No issues are reported by the code.

The only clue is that Oultook reports "This message has extra line breaks". I actually don't know if there is a relationship between both.

Cheers..

**Comment by rjohnsondev** [comment]
I've noticed this myself once when I was attempting to test the OST 2013 branch, it looks like the data may be there in the node but at a different attribute address, however it's not obvious how to determine what attribute to use (the docs just say use the current one).  Are you able to provide example PSTs?

**Comment by ggutierrezc** [comment]
Hi Richard,
Quite complex to sent you the email that is causing this issue, I have a PST file with more than 32,000 documents and have no clue how to extract that one. 
I will ask my client to generate a PST file with that single email, and will send it to you as soon as I have it.
Thanks
GG

Date: Tue, 30 Jun 2015 02:28:14 -0700
