### ISSUE TITLE
getBody,getRTFBody & getBodyHtml returns ""

### ISSUE THREAD

**Issue by rahul2611** [rjohnsondev/java-libpst#34]
I want to send u that pst  for which i was not getting correct body string.so that u can get idea..plz reply me as early as possible on my ID-rahul_it26@yahoo.com.

**Comment by rjohnsondev** [comment]
I understand this was probably too long ago (hence closing) however I have more time these days to try and address these issues, so don't hesitate to re-open if you are in a position to help me look into it further.
