### ISSUE TITLE
Twice get(Calendar.YEAR) in if condition (PSTAppointmentRecurrence)

### ISSUE THREAD

**Issue by farnulfo** [rjohnsondev/java-libpst#35]
https://github.com/rjohnsondev/java-libpst/blob/develop/src/main/java/com/pff/PSTAppointmentRecurrence.java#L267

						Calendar c = Calendar.getInstance(stz);
						c.setTime(replaceTime);
						if ( c.get(Calendar.YEAR) == ModifiedInstanceDates[i].get(Calendar.YEAR) &&
							 c.get(Calendar.MONTH) == ModifiedInstanceDates[i].get(Calendar.MONTH) &&
							 c.get(Calendar.YEAR) == ModifiedInstanceDates[i].get(Calendar.YEAR) )
						{
	/*							System.out.println("\tEmbedded Message matched"); /**/

							Exceptions[i].setEmbeddedMessage(embeddedMessage);
							break;
						}

**Comment by farnulfo** [comment]
Hi,

This issue is still here in develop branch:
https://github.com/rjohnsondev/java-libpst/blob/develop/src/main/java/com/pff/PSTAppointmentRecurrence.java#L292

May be it wasn't clear: the problem is that there is a same condition in the if :

`                  if ( c.get(Calendar.YEAR) == ModifiedInstanceDates[i].get(Calendar.YEAR) &&
                         c.get(Calendar.MONTH) == ModifiedInstanceDates[i].get(Calendar.MONTH) &&
                         c.get(Calendar.YEAR) == ModifiedInstanceDates[i].get(Calendar.YEAR) )
`

Did you mean that instead ? :
`                     if ( c.get(Calendar.YEAR) == ModifiedInstanceDates[i].get(Calendar.YEAR) &&
                         c.get(Calendar.MONTH) == ModifiedInstanceDates[i].get(Calendar.MONTH) &&
                         c.get(Calendar.DAY_OF_MONTH) == ModifiedInstanceDates[i].get(Calendar.DAY_OF_MONTH) )
`

**Comment by rjohnsondev** [comment]
ugh, I knew I would miss something important with my cleanup frenzy; thanks for the clarification and bringing it to my attention.
