### ISSUE TITLE
sub folders not detected

### ISSUE THREAD

**Issue by tommy9114** [rjohnsondev/java-libpst#38]
Hi guys, i was parsing some pst files and i noticed that there where some folders that were not detected and returned by PSTFolder#getSubFolders().
I had a "incoming" folders with 4000 messages and 2 sub folders : "important" and "support" with 5 messages and 4900 messages. these two are not returned by the method moreover also PSTFolder#getSubFolderCount() returns 0.
I was not able to figure out any other way to retrieve those folders, do you have any idea why this happens?
(c++ api by microsoft correctly find those folders)

Thanks

**Comment by rperla** [comment]
I too have the above issue when working with JAVA API. does someone has any workaround for this?

**Comment by rjohnsondev** [comment]
I'm happy to try and dig into this a little if an example PST file demonstrating the problem could be provided?

**Comment by rperla** [comment]
I can not share the file as it is confidential. The problem I have identified is, I can get the sub folders up to 2 levels, I mean i can get root folder and its sub folders. But I can not get the folders associated with each sub folder.

**Comment by rjohnsondev** [comment]
okay, I've pushed a change to the 2014-ost-support branch which may help; it seems that the marker for "hasSubfolders" which the sub-folder code was referencing is not always correctly set in the PST.
