### ISSUE TITLE
Error when iterating items inside folder 

### ISSUE THREAD

**Issue by lasithc** [rjohnsondev/java-libpst#39]
When iterating items inside folder I am getting following exception. My code is,

```java
if (folder.getContentCount() > 0) {
      PSTMessage email = (PSTMessage)folder.getNextChild();
      while (email != null) {

        //Processing attachments
        int numberOfAttachments = email.getNumberOfAttachments();
        for (int x = 0; x < numberOfAttachments; x++) {
          PSTAttachment pstAttachment = email.getAttachment(x);
         // Do attachment processing 
        }
        email = (PSTMessage)folder.getNextChild(); //This is the place exception throwing 
      }
    }
```
com.pff.PSTException: Invalid NodeInfo parameters: start 37484 is greater than end 13
        at com.pff.PSTTable$NodeInfo.<init>(PSTTable.java:186)
        at com.pff.PSTTable.getNodeInfo(PSTTable.java:265)
        at com.pff.PSTTableBC.<init>(PSTTableBC.java:125)
        at com.pff.PSTObject.detectAndLoadPSTObject(PSTObject.java:649)
        at com.pff.PSTFolder.getNextChild(PSTFolder.java:291)

**Comment by rjohnsondev** [comment]
Hi, if you are able to check if this is still a problem with the latest code and let me know that would be great.
