### ISSUE TITLE
com.pff.PSTException: Unable to find node when iterating items inside folder 

### ISSUE THREAD

**Issue by lasithc** [rjohnsondev/java-libpst#40]
When iterating items inside folder I am getting following exception. My code is,

```java
if (folder.getContentCount() > 0) {
      PSTMessage email = (PSTMessage)folder.getNextChild();
      while (email != null) {

        //Processing attachments
        int numberOfAttachments = email.getNumberOfAttachments();
        for (int x = 0; x < numberOfAttachments; x++) {
          PSTAttachment pstAttachment = email.getAttachment(x);
         // Do attachment processing 
        }
        email = (PSTMessage)folder.getNextChild(); //This is the place exception throwing 
      }
    }
```
com.pff.PSTException: Unable to find node: 1402
        at com.pff.PSTFile.findBtreeItem(PSTFile.java:721)
        at com.pff.PSTFile.getOffsetIndexNode(PSTFile.java:749)
        at com.pff.PSTObject.detectAndLoadPSTObject(PSTObject.java:649)
        at com.pff.PSTFolder.getNextChild(PSTFolder.java:291)

**Comment by rjohnsondev** [comment]
I understand this was probably too long ago (hence closing) however I have more time these days to try and address these issues, so don't hesitate to re-open if you are in a position to help me look into it further.  Some of the recent changes may have also addressed this issue.

**Comment by Ankit-Jindal** [comment]
I am still getting the same error. Took the latest code.

**Comment by gervaisb** [comment]
I have it too. Tried with the latest version and the sources from **develop** [ 5fd2c75](https://github.com/rjohnsondev/java-libpst/commit/5fd2c7553b3b9569bacf17faccb9a692fab459e7).

This occurs when using `PSTFolder#getNextChild()` within the _Tasks_ folder. Same message but different index:
> Unable to find node: 0 is desc: true 
> // Same message 77 times
> Unable to find node: -268435456 is desc: true 
> // Same message 99 times
> Unable to find node: 0 is desc: true 
> Unable to find node: 0 is desc: true 
> Unable to find node: -2147483648 is desc: true
> ...

The `TestGui` also fails before opening.
> com.pff.PSTException: Can't get child folders for folder Reminders(524323) child count: 37 - com.pff.PSTException: Unable to find 524334 is desc: true
> 	at com.pff.PSTFolder.initSubfoldersTable(PSTFolder.java:137)
> 	at com.pff.PSTFolder.getSubFolders(PSTFolder.java:92)
> 	at example.TestGui.buildTree(TestGui.java:355)
> 	at example.TestGui.buildTree(TestGui.java:356)
>	at example.TestGui.buildTree(TestGui.java:356)
>	at example.TestGui.<init>(TestGui.java:220)
>	at example.TestGui.main(TestGui.java:471)
> Caused by: com.pff.PSTException: Unable to find 524334 is desc: true
> 	at com.pff.PSTFile.findBtreeItem(PSTFile.java:756)
> 	at com.pff.PSTFile.getDescriptorIndexNode(PSTFile.java:773)
> 	at com.pff.PSTFolder.initSubfoldersTable(PSTFolder.java:125)
> 	... 6 more

And the cli `Test` fail after dumping a lot of my mails :
> com.pff.PSTException: Unable to find node: 0 is desc: true
>	at com.pff.PSTFile.findBtreeItem(PSTFile.java:760)
>	at com.pff.PSTFile.getDescriptorIndexNode(PSTFile.java:773)
>	at com.pff.PSTFolder.getNextChild(PSTFolder.java:305)
>	at example.Test.processFolder(Test.java:50)
>	at example.Test.processFolder(Test.java:39)
>	at example.Test.processFolder(Test.java:39)
>	at example.Test.processFolder(Test.java:39)
>	at example.Test.processFolder(Test.java:39)
>	at example.Test.<init>(Test.java:19)
>	at example.Test.main(Test.java:12)

**Comment by pradeep-pal** [comment]
Hi,
Still getting the below exception
com.pff.PSTException: Unable to find 1971869006 is desc: true
	at com.pff.PSTFile.findBtreeItem(PSTFile.java:756)
	at com.pff.PSTFile.getDescriptorIndexNode(PSTFile.java:773)
	at com.pff.PSTFolder.getNextChild(PSTFolder.java:305)
	at App.processFolder(App.java:100)

for the below piece of code
		if (folder.getContentCount() > 0) {
			depth++;
			PSTMessage email = (PSTMessage)folder.getNextChild();
			while (email != null) {
					printDepth();
					email = (PSTMessage)folder.getNextChild();
				}

**Comment by schaitl** [comment]
We are also getting these kinds of exceptions quite regularly, so it would be great if @rjohnsondev could reopen the issue.

**Comment by Marten4n6** [comment]
I get these errors when I try to add multithreading, so if that's what you're trying to do the cause is probably that.

**Comment by bcaessens** [comment]
I just got acquainted with this excellent toolbox. But I get this error too trying to run the TestGui.java with the example dist-list.pst as the pst file

This is the output
com.pff.PSTException: Can't get child folders for folder All Messages(1827) child count: 3 - com.pff.PSTException: Unable to find 1838 is desc: true
	at com.pff.PSTFolder.initSubfoldersTable(PSTFolder.java:138)
	at com.pff.PSTFolder.getSubFolders(PSTFolder.java:93)
	at example.TestGui.buildTree(TestGui.java:215)
	at example.TestGui.buildTree(TestGui.java:216)
	at example.TestGui.<init>(TestGui.java:76)
	at example.TestGui.main(TestGui.java:333)
Caused by: com.pff.PSTException: Unable to find 1838 is desc: true
	at com.pff.PSTFile.findBtreeItem(PSTFile.java:812)
	at com.pff.PSTFile.getDescriptorIndexNode(PSTFile.java:828)
	at com.pff.PSTFolder.initSubfoldersTable(PSTFolder.java:126)
	... 5 more
Using intellij IDEA with maven. Fairly new to java development though (coming from python).

Could you have a look. 
Bernie

**Comment by bcaessens** [comment]
As an update, if I run Test.java with this dist-list.pst, it works perfectly fine! 
I actually used this library from R through Rjava and this worked also. However, rjava started acting out with an update of R so I had to resort to the original java approach. 
Thanks in advance,
Bernie.

**Comment by Marten4n6** [comment]
Hello,

The folder "All Messages" may be a special folder used by email clients to display every message, but could not contain anything.
You can skip the processing of these folders with:
`if (folder.getNodeType() != 3) {`
Make sure you log this correctly and possibly do a try-catch for the first child as an extra check.

Kind regards,
Marten
