### ISSUE TITLE
get rfc 2822 email object

### ISSUE THREAD

**Issue by mallakimahdi** [rjohnsondev/java-libpst#42]
@rjohnsondev 
is there any way to convert PSTMessage to rfc2822 (mime email object) ?
(I want this to calculate checksum of email object)

**Comment by rjohnsondev** [comment]
Hey @mallakimahdi, AFAIK the email is not stored in its original unparsed form in PST.

I've previously used a combination of the java mail API, getBody, getBodyHTML, getTransportMessageHeaders and the various flags and attachment methods to generate MimeMessage with the same content as the PST content and then use MimeMessage.writeTo to export a RFC822 format; however this will obviously differ in structure to the original source email and therefore may not be suitable for what you are trying to do.
