### ISSUE TITLE
Extracting contact information

### ISSUE THREAD

**Issue by ggutierrezc** [rjohnsondev/java-libpst#44]
Clearly this is not an issue but I didn't find a different location to ask for help.
Does any one can provide a piece of code that I can use as a base for extracting all the contact information from a pst file?
Thanks a lot.

**Comment by rjohnsondev** [comment]
unfortunately it seems that PST files, especially those generated when using exchange server, don't contain very well structured data when it comes to this.  I'm still digging slowly to see if there is a way to do this but it doesn't look easy.  At this point I would suggest having a look at the transfer headers for each email and parsing them out manually.
