### ISSUE TITLE
getReceivedByAddress showing owner address

### ISSUE THREAD

**Issue by MurthyAvanithsa** [rjohnsondev/java-libpst#45]
Seems like get PSTMessage.getSentRepresentingEmailAddress() is showing the email address of the owner's address. We can see this in the TestGui as well .

**Comment by rjohnsondev** [comment]
The library just grabs the value in the corresponding MAPI entry as populated by outlook, I agree that many of these field names are poorly named, however it makes sense to follow the docs:

https://github.com/rjohnsondev/java-libpst/blob/develop/src/main/java/com/pff/PSTMessage.java#L173
https://msdn.microsoft.com/en-us/library/office/cc839552.aspx
