### ISSUE TITLE
PSTException with seek on big pst files

### ISSUE THREAD

**Issue by RaniRaven** [rjohnsondev/java-libpst#46]
Any one got this : PSTException("Unable to seek past end of item! ...) ?
There is a very weird phenomenon, it seems like when running the sample,
things are working fine, but running the same code as a udf from hive for example
will yield this exception, as if some pointers are getting garbaged somehow when
processing big pst files.

**Comment by rjohnsondev** [comment]
hmm, could the PST file be shared across more than one thread? (the library is not threadsafe and requires each thread have it's own PSTFile), I've come across this when the file position is changed by a different thread...

**Comment by RaniRaven** [comment]
ok, Now we have the problem. when pff reads from a stream it calls through a stream interface that has the following:
    public int read(byte[] target) 
when calling this function, u should provide a buffer, and the return value will return the number of bytes actually written up the buffer. if its -1, you've reached the end of the stream, otherwise, u should keep reading. now this  pff code does not do it and seem to assume that every call to stream.read(buffer) will fill up the buffer, and so totally disregards the returned number of bytes read!
when reading an hdfs file though, if the actual file is split, then some reads will return only part of the requested buffrer, with consecutive reads succeeding of course (this would be the same when reading from a network stream).  that's why the problem is manifested sometimes (depends on how many splits, the size of the splits, what location on the pst file it is etc). in short, this is a pff bug.

**Comment by rjohnsondev** [comment]
Thanks for digging and apologies for the amateur bug.

I am going through the process of testing this branch https://github.com/rjohnsondev/java-libpst/tree/feature/fix-read, it would be massively appreciated if you could check it out and confirm it fixes the issue.

**Comment by RaniRaven** [comment]
O.k.

I read the change, and it will work fine with my issue. It is just that you made a breaking change to the API. So If I may, I would suggest :

class PSTFileContent now looks like this:

public abstract class PSTFileContent {
    public abstract void seek(long index) throws IOException;

    public abstract long getFilePointer() throws IOException;

    public abstract int read() throws IOException;

    public abstract int read(byte[] target) throws IOException;

    public abstract void readCompletely(byte[] target) throws IOException;

    public abstract byte readByte() throws IOException;

    public abstract void close() throws IOException;
}
readCompletely() is a breaking change, for no apparent good reason. instead of declaring it abstract, i suggest providing a default implementation so it will look like this:

public abstract class PSTFileContent {
    public abstract void seek(long index) throws IOException;

    public abstract long getFilePointer() throws IOException;

    public abstract int read() throws IOException;

    public abstract int read(byte[] target) throws IOException;

    public void readCompletely(final byte[] target) throws IOException {
        int read =  this.read(target);
        if (read <=0 || read == target.length) return; //bail in common case

        byte[] buffer = new byte[8192]; 
        int offset = read;
        while (offset<target.length)
        {
            read = this.read.read(buffer);
            if (read <=0) break;
            System.arraycopy(buffer, 0, target, offset, read);
            offset+=read;
        }

    }

    public abstract byte readByte() throws IOException;

    public abstract void close() throws IOException;
}

**Comment by rjohnsondev** [comment]
yep, good point; I've made the recommended change but haven't been able to test it thoroughly just yet

**Comment by rjohnsondev** [comment]
I've run this over the PSTs I have available and seems to work correctly, thanks for your help.
