### ISSUE TITLE
Hebrew letters in email will crash code - Fix inside

### ISSUE THREAD

**Issue by YuvalPapish** [rjohnsondev/java-libpst#48]
Issue - Reading emails with Hebrew of Outlook 2016 (and most likely all other versions) will crash due to an unsupported encoding.

Root cause - Outlook use an unsupported encoding *name* for a supported encoding.

Solution - Replace the encoding name used by Outlook with the name known to Java.

The fixed code is attached.

[PSTObject.zip](https://github.com/rjohnsondev/java-libpst/files/573488/PSTObject.zip)

**Comment by rjohnsondev** [comment]
thanks very much for the bug report and fix, I'll hopefully get to it in the coming days.

I understand it's inconvenient, but it would be fantastic if you were also able to provide a tiny PST file containing an example Hebrew message? This would help me validate the fix and create a test.

**Comment by sandev1** [comment]
I had the same issue for arabic ,i solved it by editting the file PSTObject.java from line 326 as follows:
` if (codepage == null) {
                return new String(data);
            } else {
                codepage = codepage.toUpperCase(Locale.US);

             // changes ...
                try {
                      return new String(data, codepage);
                 } catch ( UnsupportedEncodingException e){
                      return new String(data, "UTF-8");
                 }
             //
}`


kindly fix this issue asap to be able to use maven dependency and remove my changes.
Thank You

**Comment by karandaftary** [comment]
Hello, 
I'm getting the following error message: 
_main.java.com.pff.PSTException: Unrecognised PST File version: 37_

My scenario: I'm trying to parse an Outlook 2016 OST file. 
Thank you
