### ISSUE TITLE
PSTException: Can't get child folders for folder SPAM Search Folder 2(8739) child count: 0 - com.pff.PSTException: Unable to find 8750 is desc: true

### ISSUE THREAD

**Issue by moberhuber** [rjohnsondev/java-libpst#50]
I've compiled java-libpst from master as per 8-Nov-2018. Running the TestGui against my large 2014 E-Mail Archive, I'm getting this error:

   PSTException: Can't get child folders for folder SPAM Search Folder 2(8739) child count: 0 - com.pff.PSTException: Unable to find 8750 is desc: true
	at com.pff.PSTFolder.initSubfoldersTable(PSTFolder.java:135)
	at com.pff.PSTFolder.getSubFolders(PSTFolder.java:90)
	at example.TestGui.buildTree(TestGui.java:354)
	at example.TestGui.<init>(TestGui.java:219)
	at example.TestGui.main(TestGui.java:470)

I'd be happy to help investigation or coding if you'd show me where to get started...

**Comment by rjohnsondev** [comment]
Yeah, this one is a "known-issue".  As it's a search folder, it doesn't actually contain any actual messages (as I understand it), it's just a container of a search index into other messages.  Fine to ignore basically.

I'll leave this open as a reminder to have the library omit traversal of these folders.

**Comment by moberhuber** [comment]
I've pushed a fix for this, could my pull request be considered ?
https://github.com/rjohnsondev/java-libpst/pull/51

**Comment by rjohnsondev** [comment]
Yes! looks good, thanks for the bump.
