### ISSUE TITLE
Issues parsing PST using PSTFile byte array constructor

### ISSUE THREAD

**Issue by jvanvalkenburgh** [rjohnsondev/java-libpst#53]
Hi, I am trying to use the option of initializing a PSTFile via a byte array, so that I don't have to download PSTs to disk before processing. I have gotten different results via the byte array constructor, and I can't find any issues with PSTByteFileContent to account for this.  I'm hoping someone may have an idea of the subtleties here.

I can call PSTFile(file) and iterate through a ~1Gb file without issue.  If I read that same file into a byte array (in my case using Apache Commons IOUtils to consume an InputStream) I get an exception:

> com.pff.PSTException: Unable to parse table, can't find BTHHEADER header information: 255 (PSTTable.java:137)

And eventually I cannot proceed past ~30 items in the PST before getting the exception.

I'm using Scala so the code is:

`val pstFile = new PSTFile (IOUtils.toByteArray(new FileInputStream (new File(fileName))))`
..
. iterate though the PST..for about 30 items.

Doing this via a straight File for the same data works and I can read all 30K items in the PST - but my intent is to pull the PST from an HTTP stream and I do not want to write the contents to disk first, which is what I've been forced to do, as my servers are IO-bound and writing to disk comes at great penalty.

`val pstFile = new PSTFile (new File(fileName))`

On the same file works fine.  I have issues with small and large files.

Any pointers appreciated - and thanks to @pineapplemachine for this method in the first place.

**Comment by pineapplemachine** [comment]
I unfortunately do not have an environment set up to check for myself, but it seems plausible that the failure could be occurring [here](https://github.com/rjohnsondev/java-libpst/blob/develop/src/main/java/com/pff/PSTTable.java#L127) as a result of an integer overflow in the `seek` method, which might be resulted by replacing all occurrences of `int` in `PSTByteFileContent.java` with `long`. (Though that seems questionable, given that the maximum size of an array in Java appears to be less than the highest representable value using an `int`.) Perhaps it's possible that not all of the data is being correctly stored in the array, or that some data is being stored incorrectly?

**Comment by rjohnsondev** [comment]
okay, I think I've been able to replicate; will let you know what I find.

**Comment by rjohnsondev** [comment]
So this looks like it is caused by java padding larger data types with set bits if the value of the smaller data type has the most significant bit set. ie:

        System.out.println(((int)(byte)0xFF) == 0xffffffff); // true
        System.out.println(((int)(byte)0xFF) < 0); // true

this should do the trick: https://github.com/rjohnsondev/java-libpst/commit/ebd1d8dd5cc2a676014488575be11d3359b2f36d

If you are able to confirm that this work for you @jvanvalkenburgh, let me know and I'll merge the branch.

**Comment by pineapplemachine** [comment]
Java just keeps on surprising me with its bizarre design decisions

**Comment by jvanvalkenburgh** [comment]
Thank you so much!  Indeed this fixed the issue, and now the results are the same regardless of constructor method.
I really appreciate the rapid help, and my thanks for an excellent library.  Regards, Jason

**Comment by weyndahir** [comment]
this is a great work, I have quick question I am not seeing in your code the exchange server properties how you connecting the server?

**Comment by rawadmarji** [comment]
can we have a new release to fix this issue
