### ISSUE TITLE
InputStream :)

### ISSUE THREAD

**Issue by casimirenslip** [rjohnsondev/java-libpst#9]
Hi,

First of all, thanks for your time spent on this project.

Next, is there a way to add or change the class PSTFile to read not a file but a generic InputStream ?

Moreover, I wish to parse only headers (to save time, memory etc)... like parsing only PSTObjects (analyse PSTObjects id)

Why ? I need to check changes in a remote PST file, so all I have is an inputstream. The pst file is very big (I can't download it each time for reading it locally), so it would be great if reading headers very fast with stream can be done with java-libpst ! 

thanks ;)

PS : I saw "seek" on the RandomAccessFile and I am not sure if there are only forward jumps and not "backwards" (no seek function in InputStream ... only skip :( :)

**Comment by lasithc** [comment]
Hi casimirenslip,

**Comment by casimirenslip** [comment]
Mmmmmh I don't remember well, however I forked the project (at that time, so it 's an old version).
However, the logic is the same https://github.com/casimirenslip/java-libpst/tree/master/com/pff/source
It's very simple : you have to replace PSTFile with _RandomAccessPSTSource which is an interface, next implement the interface to match your Stream.

I remember I did it to implement a generic Stream toconnect with a database or/and a FTPFile access from commons net project.
